apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: ci
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: ${GITHUB_USER}
  password: ${GITHUB_PASSWORD}
