apiVersion: v1
kind: Pod
metadata:
  name: tcpdump
  namespace: psp-example
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: tcpdump
    image: ghcr.io/tom1299/tekton-examples/network-tools:latest
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add: ["NET_RAW"]
  imagePullSecrets:
  - name: regcred-ghcr
